mkdir histos
mkdir histos/latest_production

rm histos/latest_production/*2018*.root

python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_DY10to50_2018.root histos/latest_production/ZEMuHistos_DY10to50_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_DY50_2018.root histos/latest_production/ZEMuHistos_DY50_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT100to200_2018.root histos/latest_production/ZEMuHistos_QCDHT100to200_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT200to300_2018.root histos/latest_production/ZEMuHistos_QCDHT200to300_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT300to500_2018.root histos/latest_production/ZEMuHistos_QCDHT300to500_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT500to700_2018.root histos/latest_production/ZEMuHistos_QCDHT500to700_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT700to1000_2018.root histos/latest_production/ZEMuHistos_QCDHT700to1000_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT1000to1500_2018.root histos/latest_production/ZEMuHistos_QCDHT1000to1500_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_QCDHT1500to2000_2018.root histos/latest_production/ZEMuHistos_QCDHT1500to2000_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_SingleAntiToptW_2018.root histos/latest_production/ZEMuHistos_SingleAntiToptW_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_SingleToptW_2018.root histos/latest_production/ZEMuHistos_SingleToptW_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_WW_2018.root histos/latest_production/ZEMuHistos_WW_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_WZ_2018.root histos/latest_production/ZEMuHistos_WZ_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_ttbarZlnu_2018.root histos/latest_production/ZEMuHistos_ttbarZlnu_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_ttbarlnu_2018.root histos/latest_production/ZEMuHistos_ttbarlnu_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_ttbarToHadronic_2018.root histos/latest_production/ZEMuHistos_ttbarToHadronic_2018.root
python generate_histos.py 2 rootfiles/latest_production/MC/backgrounds/ZEMuAnalysis_ttbarToSemiLeptonic_2018.root histos/latest_production/ZEMuHistos_ttbarToSemiLeptonic_2018.root

python generate_histos.py 2 rootfiles/latest_production/MC/signals/ZEMuAnalysis_Signal_2018.root histos/latest_production/ZEMuHistos_Signal_2018.root

#Merge samples
hadd histos/latest_production/ZEMuHistos_QCD_2018.root histos/latest_production/ZEMuHistos_QCDHT*_2018.root
rm histos/latest_production/ZEMuHistos_QCDHT*_2018.root

hadd histos/latest_production/ZEMuHistos_STtW_2018.root histos/latest_production/ZEMuHistos_Single*ToptW_2018.root
rm histos/latest_production/ZEMuHistos_Single*ToptW_2018.root

hadd histos/latest_production/ZEMuHistos_DY_2018.root histos/latest_production/ZEMuHistos_DY*50_2018.root
rm histos/latest_production/ZEMuHistos_DY*50_2018.root

hadd histos/latest_production/ZEMuHistos_ttbar_2018.root histos/latest_production/ZEMuHistos_ttbarTo*nic_2018.root
rm histos/latest_production/ZEMuHistos_ttbarTo*nic_2018.root
